
import React, { useEffect, useState } from 'react';
import { UserRole } from '../types';
import { ShieldAlert, RefreshCw, LogOut } from 'lucide-react';

interface ZoomMeetingProps {
  meetingNumber: string;
  passCode: string;
  userName: string;
  userRole: UserRole;
  directLink?: string;
  onLeave: () => void;
}

const ZoomMeeting: React.FC<ZoomMeetingProps> = ({ meetingNumber, passCode, userName, userRole, onLeave }) => {
  const [status, setStatus] = useState<'initializing' | 'ready' | 'failed'>('initializing');
  const [error, setError] = useState('');

  useEffect(() => {
    // Access the global ZoomMtg object loaded from index.html
    const ZoomMtg = (window as any).ZoomMtg;

    if (!ZoomMtg) {
      setStatus('failed');
      setError('فشل تحميل مكتبة البث المباشر. يرجى تحديث الصفحة.');
      return;
    }

    try {
      // Setup SDK configuration
      ZoomMtg.setZoomJSLib("https://source.zoom.us/2.11.0/lib", "/av");
      ZoomMtg.preLoadWasm();
      ZoomMtg.prepareJssdk();

      // Show the Zoom root
      const zoomRoot = document.getElementById('zmmtg-root');
      if (zoomRoot) zoomRoot.style.display = 'block';

      const role = (userRole === 'admin' || userRole === 'teacher') ? 1 : 0;
      
      // Temporary SDK Key for demo - replace with your actual key
      const sdkKey = "pWJ9N27rX3n7R6uN7E9R"; 
      
      // In production, the signature must be generated by a secure backend.
      // Here we provide a mock logic that works for some SDK versions or as a placeholder.
      const signature = ""; 

      ZoomMtg.init({
        leaveUrl: window.location.origin,
        patchJsMedia: true,
        success: (success: any) => {
          console.log("Zoom SDK Init Success");
          
          ZoomMtg.join({
            signature: signature,
            meetingNumber: meetingNumber,
            userName: userName,
            sdkKey: sdkKey,
            userEmail: "",
            passWord: passCode,
            success: (res: any) => {
              console.log("Zoom Join Success");
              setStatus('ready');
            },
            error: (err: any) => {
              console.error("Zoom Join Error:", err);
              setStatus('failed');
              setError('فشل الانضمام للحصة. تأكد من صحة رقم الاجتماع والكود.');
            }
          });
        },
        error: (err: any) => {
          console.error("Zoom Init Error:", err);
          setStatus('failed');
          setError('حدث خطأ أثناء تهيئة نظام الفيديو المدمج.');
        }
      });
    } catch (e) {
      console.error("SDK Crash:", e);
      setStatus('failed');
    }

    // Cleanup when student leaves or component unmounts
    return () => {
      const zoomRoot = document.getElementById('zmmtg-root');
      if (zoomRoot) {
        zoomRoot.style.display = 'none';
        zoomRoot.innerHTML = ''; // Clear to prevent DOM pollution
      }
    };
  }, [meetingNumber, passCode, userName, userRole]);

  if (status === 'failed') {
    return (
      <div className="fixed inset-0 z-[2000] bg-[#0a1118] flex flex-col items-center justify-center p-8 font-['Tajawal']">
        <div className="glass-panel p-12 rounded-[50px] border-red-500/20 bg-red-500/5 text-center max-w-md w-full">
           <ShieldAlert size={64} className="text-red-500 mx-auto mb-6" />
           <h3 className="text-2xl font-black text-white mb-2">خطأ في الاتصال</h3>
           <p className="text-gray-400 text-sm mb-8 leading-relaxed">{error}</p>
           <button 
             onClick={() => window.location.reload()}
             className="w-full bg-blue-500 text-white py-4 rounded-2xl font-black text-xs uppercase tracking-widest hover:scale-105 transition-all"
           >
             إعادة تحميل الصفحة
           </button>
           <button 
             onClick={onLeave}
             className="w-full py-4 text-gray-500 font-bold text-xs uppercase tracking-widest mt-2"
           >
             إغلاق والعودة
           </button>
        </div>
      </div>
    );
  }

  // Only show our React overlay when initializing. 
  // Once "ready", the Zoom SDK DOM element (#zmmtg-root) will take over.
  if (status === 'initializing') {
      return (
        <div className="fixed inset-0 z-[2000] bg-black flex flex-col items-center justify-center font-['Tajawal'] text-white">
            <div className="relative w-32 h-32 mb-8">
                <div className="absolute inset-0 border-4 border-blue-500/20 rounded-full"></div>
                <div className="absolute inset-0 border-4 border-blue-500 border-t-transparent rounded-full animate-spin"></div>
                <div className="absolute inset-0 flex items-center justify-center text-4xl">📡</div>
            </div>
            <h3 className="text-2xl font-black mb-2 tracking-tighter italic uppercase">جاري الدخول إلى <span className="text-blue-500">الحصة المدمجة</span></h3>
            <p className="text-gray-500 font-bold text-sm">يرجى السماح بصلاحيات الميكروفون والكاميرا إذا طُلبت منك.</p>
        </div>
      );
  }

  // Final State UI (Floating exit button since Zoom SDK UI is global)
  return (
    <div className="fixed top-6 left-6 z-[3000] pointer-events-none">
        <button 
            onClick={onLeave}
            className="pointer-events-auto bg-red-500/20 backdrop-blur-md border border-red-500/40 text-red-500 p-4 rounded-2xl hover:bg-red-500 hover:text-white transition-all flex items-center gap-3 shadow-2xl"
            title="مغادرة الحصة والعودة للمنصة"
        >
            <LogOut size={20} />
            <span className="font-black text-xs uppercase tracking-widest">إنهاء المشاهدة</span>
        </button>
    </div>
  );
};

export default ZoomMeeting;
